#!/usr/bin/env python3
"""
Generate secure passwords for all services and save them to .env file
"""
import secrets
import string
import os
from pathlib import Path

def generate_password(length=32):
    """Generate a secure random password"""
    # Use alphanumeric characters and some special characters that are safe for most systems
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    password = ''.join(secrets.choice(alphabet) for i in range(length))
    return password

def main():
    """Generate passwords for all services"""
    # Define all the passwords we need
    passwords = {
        'POSTGRES_PASSWORD': generate_password(),
        'POSTGRES_USER': 'jware_trader',
        'POSTGRES_DB': 'jware_trader_db',
        'REDIS_PASSWORD': generate_password(),
        'JWT_SECRET': generate_password(64),  # Longer for JWT
        'API_GATEWAY_SECRET': generate_password(),
        'ADMIN_PASSWORD': generate_password(),
        'ENCRYPTION_KEY': generate_password(32),
    }
    
    # Path to .env file
    env_path = Path(__file__).parent.parent / '.env'
    
    # Create or update .env file
    with open(env_path, 'w') as f:
        f.write("# Auto-generated passwords - DO NOT COMMIT THIS FILE\n")
        f.write("# Generated by scripts/generate-passwords.py\n\n")
        
        # Write database configuration
        f.write("# Database Configuration\n")
        f.write(f"POSTGRES_USER={passwords['POSTGRES_USER']}\n")
        f.write(f"POSTGRES_PASSWORD={passwords['POSTGRES_PASSWORD']}\n")
        f.write(f"POSTGRES_DB={passwords['POSTGRES_DB']}\n")
        f.write("POSTGRES_HOST=postgres\n")
        f.write("POSTGRES_PORT=5432\n\n")
        
        # Write Redis configuration
        f.write("# Redis Configuration\n")
        f.write(f"REDIS_PASSWORD={passwords['REDIS_PASSWORD']}\n")
        f.write("REDIS_HOST=redis\n")
        f.write("REDIS_PORT=6379\n\n")
        
        # Write security configuration
        f.write("# Security Configuration\n")
        f.write(f"JWT_SECRET={passwords['JWT_SECRET']}\n")
        f.write(f"API_GATEWAY_SECRET={passwords['API_GATEWAY_SECRET']}\n")
        f.write(f"ADMIN_PASSWORD={passwords['ADMIN_PASSWORD']}\n")
        f.write(f"ENCRYPTION_KEY={passwords['ENCRYPTION_KEY']}\n\n")
        
        # Write service URLs
        f.write("# Service URLs\n")
        f.write("TRADING_ENGINE_URL=http://trading-engine:8000\n")
        f.write("MARKET_DATA_URL=http://market-data:8001\n")
        f.write("API_GATEWAY_URL=http://api-gateway:3000\n")
        f.write("WEB_UI_URL=http://web-ui:3001\n\n")
        
        # Write environment
        f.write("# Environment\n")
        f.write("NODE_ENV=development\n")
        f.write("PYTHON_ENV=development\n")
    
    print("✅ Passwords generated and saved to .env file")
    print(f"📁 Location: {env_path}")
    print("\n⚠️  IMPORTANT: Never commit the .env file to version control!")
    
    # Also create .env.example with placeholder values
    example_path = Path(__file__).parent.parent / '.env.example'
    with open(example_path, 'w') as f:
        f.write("# Example environment variables - Copy to .env and fill with actual values\n\n")
        f.write("# Database Configuration\n")
        f.write("POSTGRES_USER=your_db_user\n")
        f.write("POSTGRES_PASSWORD=your_secure_password\n")
        f.write("POSTGRES_DB=your_db_name\n")
        f.write("POSTGRES_HOST=postgres\n")
        f.write("POSTGRES_PORT=5432\n\n")
        f.write("# Redis Configuration\n")
        f.write("REDIS_PASSWORD=your_redis_password\n")
        f.write("REDIS_HOST=redis\n")
        f.write("REDIS_PORT=6379\n\n")
        f.write("# Security Configuration\n")
        f.write("JWT_SECRET=your_jwt_secret\n")
        f.write("API_GATEWAY_SECRET=your_api_gateway_secret\n")
        f.write("ADMIN_PASSWORD=your_admin_password\n")
        f.write("ENCRYPTION_KEY=your_encryption_key\n\n")
        f.write("# Service URLs\n")
        f.write("TRADING_ENGINE_URL=http://trading-engine:8000\n")
        f.write("MARKET_DATA_URL=http://market-data:8001\n")
        f.write("API_GATEWAY_URL=http://api-gateway:3000\n")
        f.write("WEB_UI_URL=http://web-ui:3001\n\n")
        f.write("# Environment\n")
        f.write("NODE_ENV=development\n")
        f.write("PYTHON_ENV=development\n")
    
    print(f"📁 Created .env.example: {example_path}")

if __name__ == "__main__":
    main()